services:
  quiz-mongo:
    image: mongo:7
    container_name: quiz-mongo
    restart: unless-stopped
    ports:
      - "6001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: quiz_root
      MONGO_INITDB_ROOT_PASSWORD: quiz_root_pass
    volumes:
      - quiz_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://quiz_root:quiz_root_pass@localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 }).ok" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  quiz_mongo_data: