services:
  identity-db:
    image: postgres:16-alpine
    container_name: identity-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_pass
    ports:
      - "6000:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_user -d identitydb"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  identity_db_data: